version: '3.5'

services:
  frontend:
    image: ${APP_NAME}_frontend
    container_name: ${APP_NAME}_frontend
    restart: always

  nginx:
    image: ${APP_NAME}_nginx
    container_name: ${APP_NAME}_nginx
    restart: always
    ports:
      - $HOSTPORT:80
    depends_on:
      - frontend



